apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ $.Values.microservice_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $.Values.microservice_name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.microservice_name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminate_grace_period }}
      priorityClassName: "priority-class-{{ .Values.microservice_name }}-pods"
      containers:
        - name: {{ $.Values.microservice_name }}
          image: {{ .Values.docker_image }}:{{ .Values.docker_image_tag }}
          imagePullPolicy: Always
          env:
          {{- range $key, $val := .Values.env_vars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.container_port }}
          resources:
            requests:
              memory: {{ .Values.memory_request }}
              cpu: {{ .Values.cpu_request }}
            limits:
              memory: {{ .Values.memory_limit }}
              cpu: {{ .Values.cpu_limit }}
          livenessProbe:
            httpGet:
              port: {{ .Values.container_port }}
              path: {{ .Values.health_check_path }}
            initialDelaySeconds: {{ .Values.liveness_prob_delay }}
            periodSeconds: {{ .Values.liveness_prob_period }}
          readinessProbe:
            httpGet:
              port: {{ .Values.container_port }}
              path: {{ .Values.health_check_path }}
            initialDelaySeconds: {{ .Values.readiness_prob_delay }}
            periodSeconds: {{ .Values.readiness_prob_period }}
      imagePullSecrets:
        - name: dockerconfigjson-github-com
