apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ $.Values.microservice_name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $.Values.microservice_name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.microservice_name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminate_grace_period }}
      priorityClassName: {{ .Values.microservice_name }}-pods
      containers:
        - name: {{ $.Values.microservice_name }}
          image: {{ .Values.registry.image }}:{{ .Values.registry.tag }}
          imagePullPolicy: Always
          env:
          {{- range $key, $val := .Values.env_vars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}

          {{- if .Values.secrets.enabled }}
          {{- range $key, $val := .Values.secrets.values }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val }}
                  key: SECRET_TOKEN
          {{- end }}
          {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: {{ .Values.container_port }}
          resources:
            requests:
              memory: {{ .Values.memory_request }}
              cpu: {{ .Values.cpu_request }}
            limits:
              memory: {{ .Values.memory_limit }}
              cpu: {{ .Values.cpu_limit }}
          livenessProbe:
            httpGet:
              port: {{ .Values.container_port }}
              path: {{ .Values.health_check_path }}
            initialDelaySeconds: {{ .Values.liveness_prob_delay }}
            periodSeconds: {{ .Values.liveness_prob_period }}
          readinessProbe:
            httpGet:
              port: {{ .Values.container_port }}
              path: {{ .Values.health_check_path }}
            initialDelaySeconds: {{ .Values.readiness_prob_delay }}
            periodSeconds: {{ .Values.readiness_prob_period }}
      {{- if .Values.registry.private }}
      {{- if eq .Values.registry.type "github" }}
      imagePullSecrets:
        - name: ghcr-dockerconfig
      {{- end }}
      {{- end }}
