apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.microservice_name }}-migration
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: {{ $.Values.microservice_name }}-migration
          image: {{ .Values.registry.image }}:{{ .Values.registry.tag }}
          command: ["bin/api"]
          args: ["--migrate"]
          env:
          {{- range $key, $val := .Values.env_vars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}

          {{- if .Values.secrets.enabled }}
          {{- range $key, $val := .Values.secrets.values }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val }}
                  key: SECRET_TOKEN
          {{- end }}
          {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      {{- if .Values.registry.private }}
      {{- if eq .Values.registry.type "github" }}
      imagePullSecrets:
        - name: ghcr-dockerconfig
      {{- end }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 0
