kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ $.Values.microservice_name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.microservice_name }}
  minReplicas: {{ $.Values.min_replica }}
  maxReplicas: {{ $.Values.max_replica }}
  metrics:
    # use a "Pods" metric, which takes the average of the
    # given metric across all pods controlled by the autoscaling target
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.memory_based_scale_threshold }}

    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.cpu_based_scale_threshold }}

