kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ $.Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.name }}
  minReplicas: {{ $.Values.resource.replica.min }}
  maxReplicas: {{ $.Values.resource.replica.max }}
  metrics:
    # use a "Pods" metric, which takes the average of the
    # given metric across all pods controlled by the autoscaling target
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.resource.scale_threshold.memory }}

    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.resource.scale_threshold.cpu }}
